#!/usr/bin/env python3

import csv
import sys
import os

def convert(srcfilename, destfilename):
    lines = []
    with open(srcfilename, 'rt') as csvfile:
        reader = csv.reader(csvfile, delimiter=';')
        for row in reader:
            lines.append(row)
    with open(destfilename, "wt") as csvfile:
        writer = csv.writer(csvfile)
        for row in lines:
            writer.writerow(row)


if __name__ == '__main__':
    srcfile = sys.argv[1]
    dstfile = sys.argv[2]

    assert os.path.exists(srcfile) == True
    assert os.path.exists(dstfile) == False

    convert(srcfile, dstfile)

